### ISSUE TITLE
Mac M1 install attempt continues even after unsupported architecture message

### ISSUE THREAD

**Issue by SgtPooki** [jamesstidard/asdf-qt#1]
I'm attempting to install qt using this asdf plugin on my M1 mac.

## Expected output:
```bash
asdf install qt 5.2.0-dev
Unsupported architecture: arm64.
Abandoning install.
```

## Actual output:
```bash
asdf install qt 5.2.0-dev
Unsupported architecture: arm64.
Downloading...
Download complete
Extracting...
Extraction complete
Tweaking Configs...
Tweaking /var/folders/bl/_gl5_59s11v7qz5ysd6bfgb00000gn/T//asdf-qt-zusEXQiFdw/5.2.0/clang_64/bin/qt.conf
/Users/sgtpooki/.asdf/plugins/qt/bin/install: line 190: /var/folders/bl/_gl5_59s11v7qz5ysd6bfgb00000gn/T//asdf-qt-zusEXQiFdw/5.2.0/clang_64/bin/qt.conf: No such file or directory
```

FYI: I was able to install qt successfully with `arch -x86_64 asdf install qt 5.15.2`

**Comment by jamesstidard** [comment]
Hi @SgtPooki,

I don't actually use QT too much, and I don't have a M1 Mac. Though, I was under the impression that only the newer releases of QT6.2+ support arm64.

Do you know if this should not be the case. If not, then probably a bug in my script somewhere.

**Comment by SgtPooki** [comment]
@jamesstidard you may be right about QT, i'm not positive. However, the callout I brought up here is regarding the fact that attempting to install an unsupported version doesn't cause the install to quit; and it should, right?

https://github.com/jamesstidard/asdf-qt/blob/9d2211b3d88ec0189ec3a1a2d87b91997437ea47/bin/install#L24-L25

I see that you're attempting to exit with an error code, but `asdf` doesn't seem to be respecting that.

**Comment by jamesstidard** [comment]
@SgtPooki Sorry, my mistake; I misread your initial ticket. My mind jumped to thinking it was about trying to get an install to work on an M1 Mac.

You're right, those exits were being ignored, because they are called in subshells within the rest of the script. Found this article that describes what was going on: https://cravencode.com/post/essentials/exit-shell-script-from-subshell/

I pushed a fix to that. Can `asdf plugin update qt` and give it a test if you want (I'm still without a M1 Mac 😢).

Thanks letting me know. I'll close this ticket if I hear it all goes well, or don't hear back from you in a while.

**Comment by jamesstidard** [comment]
It does also look like the newer QTs do have native arm support. I might be able to update the script one of these weekends to allow native M1 installs - if you're using the plugin and are interested in that. Though I might need your help testing it.

**Comment by SgtPooki** [comment]
your fix works
```bash
> asdf install qt 5.2.0-dev
Unsupported architecture: arm64. #end of output
```

**Comment by SgtPooki** [comment]
> It does also look like the newer QTs do have native arm support. I might be able to update the script one of these weekends to allow native M1 installs - if you're using the plugin and are interested in that. Though I might need your help testing it.

absolutely. just ping me =)
